"""Decidability-map analysis engine (§5 DV1 / H2 / H3).

This module runs the P3 evidence-decidability classifier over a structured
``{archetype τ × evidence-regime R × confidence κ}`` grid and turns the per-query
verdicts into the three research deliverables of P3:

  §5 / DV1 — the **decidability map**: for every (τ, R) cell, the fraction of a
             structured query battery that is decidable / underdetermined /
             infeasible under a given (κ, φ), with bootstrap CIs. This is the
             empirical instantiation of the §5 dependent variable DV1.
  H2 — the **blind-spot characterization**: a *descriptive* per-axis miss-rate
       (fraction of configs with zero κ-qualifying observation on each axis),
       per τ and overall. This is the only place the DB is read directly, and it
       is clearly labelled descriptive provenance — it never feeds a verdict.
  H3 — the **κ-sensitivity**: how the overall underdetermined-fraction moves as
       the confidence policy is loosened/tightened (('H','M') vs ('H',) vs
       ('H','M','L')).

C7 firewall. Every decidability computation reads the substrate ONLY through the
solver layer (`classify_query` → `classify_candidate` → `sub.cell`/`sub.candidates`).
The grid generator reads observed values through `sub.candidates(τ)` + `sub.cell()`
as well. The single exception is `blind_spot_report` (and the τ discovery in
`ARCHETYPES`), which is a *descriptive* statistic over the raw DB — it is labelled
as such and is not part of the decision-theoretic pipeline.

Determinism. Bootstrap resampling uses a locally-seeded `random.Random(12345)`
(mirroring the repo's `seed_everything` ethos): the whole map is reproducible.

Open gate Q2. The query battery generated by `generate_queries` is a STRUCTURED
GRID (every axis probed once + a curated set of realistic 2-axis bundles). It is
*not* yet a ZenML/MedHELM-justified prior over real deployment queries — the
thresholds are percentile-grounded but the query distribution is hand-built.
"""

from __future__ import annotations

import random
import sqlite3
from typing import TYPE_CHECKING

from prudent_ai.solver import (
    REGIME_LADDER,
    Decidability,
    Phi,
    classify_query,
)
from prudent_ai.solver.beliefs import DEFAULT_KAPPA
from prudent_ai.solver.query import Query, make_query

if TYPE_CHECKING:
    from prudent_ai.substrate import Substrate

# The eight right-sizing axes, in a stable order (deterministic grids).
AXES: tuple[str, ...] = (
    "quality",
    "latency_p95",
    "throughput",
    "cost",
    "energy",
    "memory_hw",
    "governance",
    "reviewer_burden",
)

# Direction of the constraint per axis. "higher-is-better" axes are bound with
# '>=' (we demand at least the median), "lower-is-better" with '<=' (we cap at the
# median). Governance / reviewer_burden are treated as quality-like ('>=' nominal).
_GE_AXES: frozenset[str] = frozenset(
    {"quality", "throughput", "governance", "reviewer_burden"}
)
_LE_AXES: frozenset[str] = frozenset(
    {"latency_p95", "cost", "energy", "memory_hw"}
)

# Nominal threshold for axes with no observed evidence — the binding is still
# *probed* (the point of H2 is that such a binding is undecidable for lack of
# evidence, whatever the number).
_NOMINAL: float = 1.0

# Curated realistic 2-axis bundles (Q2: hand-built, not yet prior-justified).
_PAIRWISE: tuple[tuple[str, str], ...] = (
    ("quality", "cost"),
    ("quality", "latency_p95"),
    ("quality", "energy"),
    ("latency_p95", "cost"),
    ("throughput", "energy"),
    ("quality", "governance"),
)

# Percentile used to set single-axis thresholds (median = a realistic mid-bar).
_GRID_PCT: int = 50

_BOOT_SEED: int = 12345

# Confidence policies swept by the κ-sensitivity analysis (H3).
_KAPPA_SWEEP: tuple[tuple[str, ...], ...] = (
    ("H", "M"),
    ("H",),
    ("H", "M", "L"),
)


# ---------------------------------------------------------------------------
# 1. Archetype discovery (descriptive — MAY read the DB directly)
# ---------------------------------------------------------------------------


def ARCHETYPES(sub: Substrate) -> list[str]:  # noqa: N802 (public constant-like)
    """Distinct τ strings present in the DB (descriptive discovery).

    Provenance: descriptive. This reads `config.tau` directly via sqlite3 — it is
    a discovery of *what archetypes exist*, not a decidability computation, so the
    C7 firewall does not apply. Expect: function-calling, inference-serving,
    general-qa.
    """
    con = sqlite3.connect(sub._db_path)  # noqa: SLF001 (descriptive read, see docstring)
    try:
        rows = con.execute("SELECT DISTINCT tau FROM config ORDER BY tau").fetchall()
    finally:
        con.close()
    return [r[0] for r in rows]


# ---------------------------------------------------------------------------
# 2. Observed thresholds (through the C7 interface)
# ---------------------------------------------------------------------------


def observed_thresholds(
    sub: Substrate,
    tau: str,
    axis: str,
    percentiles: tuple[int, ...] = (25, 50, 75),
    kappa: tuple[str, ...] = DEFAULT_KAPPA,
) -> dict[int, float]:
    """Pooled κ-filtered observed-value percentiles for (τ, axis).

    Reads through the C7 interface only: iterate `sub.candidates(τ)` and
    `sub.cell(cand.id, axis)`, keep κ-qualifying numeric values, and return the
    requested percentiles. Used to ground the grid thresholds in realistic
    values rather than magic numbers.

    Returns ``{}`` if the axis is ⊥ for this τ under κ (no qualifying evidence).
    The grid still probes such an axis with a nominal threshold.
    """
    vals: list[float] = []
    for cand in sub.candidates(tau):
        for obs in sub.cell(cand.id, axis):
            if obs.confidence in kappa and obs.value_num is not None:
                vals.append(obs.value_num)
    if not vals:
        return {}
    vals.sort()
    out: dict[int, float] = {}
    for p in percentiles:
        out[p] = _percentile(vals, p)
    return out


def _percentile(sorted_vals: list[float], pct: int) -> float:
    """Nearest-rank percentile of an already-sorted list (deterministic)."""
    if not sorted_vals:
        raise ValueError("percentile of empty list")
    if len(sorted_vals) == 1:
        return sorted_vals[0]
    # Linear-interpolation rank (matches numpy 'linear' default closely enough,
    # without the numpy dependency).
    rank = (pct / 100.0) * (len(sorted_vals) - 1)
    lo_i = int(rank)
    hi_i = min(lo_i + 1, len(sorted_vals) - 1)
    frac = rank - lo_i
    return sorted_vals[lo_i] * (1 - frac) + sorted_vals[hi_i] * frac


# ---------------------------------------------------------------------------
# 3. Query battery (structured grid — Q2 open)
# ---------------------------------------------------------------------------


def _axis_op(axis: str) -> str:
    return ">=" if axis in _GE_AXES else "<=" if axis in _LE_AXES else ">="


def _axis_threshold(sub: Substrate, tau: str, axis: str, kappa: tuple[str, ...]) -> float:
    """Median observed threshold for (τ, axis), or nominal if the axis is ⊥."""
    pcts = observed_thresholds(sub, tau, axis, (_GRID_PCT,), kappa)
    return pcts.get(_GRID_PCT, _NOMINAL)


def generate_queries(
    sub: Substrate,
    tau: str,
    kappa: tuple[str, ...] = DEFAULT_KAPPA,
) -> list[Query]:
    """Build the structured query battery for archetype τ.

    STRUCTURED GRID (open gate Q2 — not yet a ZenML/MedHELM-justified prior over
    real deployment queries):

    - Single-axis: one query per axis a ∈ the eight axes, binding on a with a
      median observed threshold ('>=' for higher-is-better quality / throughput /
      governance / reviewer_burden; '<=' for lower-is-better latency_p95 / cost /
      energy / memory_hw). Axes with no κ-evidence get a nominal threshold — the
      binding is still probed (and will be undecidable for lack of evidence; that
      is the H2 signal). Label ``bind:<axis>``.
    - Pairwise: a curated set of realistic 2-axis bundles
      (quality+cost, quality+latency_p95, quality+energy, latency_p95+cost,
      throughput+energy, quality+governance). Label ``bind:a+b``.

    A few dozen queries per τ. Thresholds are percentile-grounded (realistic), the
    query *distribution* is hand-built (Q2).
    """
    queries: list[Query] = []

    # Single-axis probes.
    for axis in AXES:
        thr = _axis_threshold(sub, tau, axis, kappa)
        queries.append(
            make_query(tau, [(axis, _axis_op(axis), thr)], label=f"bind:{axis}")
        )

    # Pairwise curated bundles.
    for a, b in _PAIRWISE:
        thr_a = _axis_threshold(sub, tau, a, kappa)
        thr_b = _axis_threshold(sub, tau, b, kappa)
        queries.append(
            make_query(
                tau,
                [(a, _axis_op(a), thr_a), (b, _axis_op(b), thr_b)],
                label=f"bind:{a}+{b}",
            )
        )

    return queries


# ---------------------------------------------------------------------------
# 4. Cell runner
# ---------------------------------------------------------------------------

_LABELS: tuple[str, ...] = (
    Decidability.DECIDABLE.value,
    Decidability.UNDERDETERMINED.value,
    Decidability.INFEASIBLE.value,
)


def run_cell(
    sub: Substrate,
    tau: str,
    regime: frozenset[str],
    kappa: tuple[str, ...],
    phi: Phi,
    queries: list[Query],
) -> dict:
    """Classify every query in a (τ, R, κ, φ) cell and tally the outcomes.

    Returns a dict with:
      - ``n``         : number of queries classified.
      - ``counts``    : {label: int}.
      - ``fractions`` : {label: float} (counts / n).
      - ``labels``    : the ordered list of per-query labels (for bootstrap).
      - ``blocking``  : {label: {axis: freq}} — per-outcome blocking-axis tally
                        (only UNDERDETERMINED carries blocking axes).
    """
    labels: list[str] = []
    counts: dict[str, int] = dict.fromkeys(_LABELS, 0)
    blocking: dict[str, dict[str, int]] = {lab: {} for lab in _LABELS}

    for q in queries:
        res = classify_query(sub, q, kappa=kappa, phi=phi, regime=regime)
        lab = res.label.value
        labels.append(lab)
        counts[lab] += 1
        for ax in res.blocking_axes:
            blocking[lab][ax] = blocking[lab].get(ax, 0) + 1

    n = len(queries)
    fractions = {lab: (counts[lab] / n if n else 0.0) for lab in _LABELS}
    return {
        "n": n,
        "counts": counts,
        "fractions": fractions,
        "labels": labels,
        "blocking": blocking,
    }


# ---------------------------------------------------------------------------
# 5. Bootstrap CIs
# ---------------------------------------------------------------------------


def bootstrap_ci(
    labels: list[str],
    n_boot: int = 1000,
) -> dict[str, tuple[float, float]]:
    """95% percentile bootstrap CI on each label's fraction.

    Resamples *labels* with replacement `n_boot` times using a locally-seeded
    `random.Random(12345)` (deterministic, repo-wide reproducibility ethos).
    Returns ``{label: (lo, hi)}`` for each of the three decidability labels.
    """
    if not labels:
        return {lab: (0.0, 0.0) for lab in _LABELS}

    rng = random.Random(_BOOT_SEED)
    n = len(labels)
    # Per-label fraction across bootstrap replicates.
    fracs: dict[str, list[float]] = {lab: [] for lab in _LABELS}
    for _ in range(n_boot):
        sample = [labels[rng.randrange(n)] for _ in range(n)]
        for lab in _LABELS:
            fracs[lab].append(sample.count(lab) / n)

    out: dict[str, tuple[float, float]] = {}
    for lab in _LABELS:
        s = sorted(fracs[lab])
        out[lab] = (_percentile(s, 2.5), _percentile(s, 97.5))
    return out


# ---------------------------------------------------------------------------
# 6. Map builder
# ---------------------------------------------------------------------------


def build_map(
    sub: Substrate,
    kappa: tuple[str, ...] = DEFAULT_KAPPA,
    phi: Phi = Phi.POINT,
    n_boot: int = 1000,
) -> dict:
    """Build the decidability map (§5 / DV1) over archetype × regime.

    ``map[tau][regime_name] = {fractions, cis, counts, blocking}`` for every
    archetype τ in the DB and every regime in `REGIME_LADDER`, under the given
    (κ, φ). All decidability computation goes through the C7 interface.
    """
    out: dict[str, dict[str, dict]] = {}
    for tau in ARCHETYPES(sub):
        queries = generate_queries(sub, tau, kappa)
        out[tau] = {}
        for regime_name, regime in REGIME_LADDER:
            cell = run_cell(sub, tau, regime, kappa, phi, queries)
            cis = bootstrap_ci(cell["labels"], n_boot=n_boot)
            out[tau][regime_name] = {
                "fractions": cell["fractions"],
                "cis": cis,
                "counts": cell["counts"],
                "blocking": cell["blocking"],
            }
    return out


# ---------------------------------------------------------------------------
# 7. Blind-spot report (DESCRIPTIVE — reads the DB directly)
# ---------------------------------------------------------------------------


def blind_spot_report(
    sub: Substrate,
    kappa: tuple[str, ...] = DEFAULT_KAPPA,
) -> dict:
    """Per-axis miss-rate over configs (DESCRIPTIVE provenance — H2).

    Miss-rate of axis a = fraction of configs that have *zero* κ-qualifying
    observation on a. Reported per τ and overall.

    Provenance: DESCRIPTIVE. This reads the raw DB directly (sqlite3) — it is a
    coverage statistic about evidence sparsity, NOT a decidability computation, so
    it sits outside the C7 firewall by design. It never feeds a verdict.

    Returns::

        {
          "provenance": "descriptive",
          "kappa": [...],
          "per_tau": {tau: {axis: miss_rate}},
          "overall": {axis: miss_rate},
          "config_counts": {tau: n_configs, "__total__": n},
        }
    """
    placeholders = ",".join("?" for _ in kappa)
    con = sqlite3.connect(sub._db_path)  # noqa: SLF001 (descriptive read, see docstring)
    try:
        taus = [r[0] for r in con.execute("SELECT DISTINCT tau FROM config").fetchall()]

        per_tau: dict[str, dict[str, float]] = {}
        config_counts: dict[str, int] = {}
        # overall accumulators: n configs with >=1 κ-obs on axis, total configs.
        overall_present: dict[str, int] = dict.fromkeys(AXES, 0)
        total_configs = 0

        for tau in taus:
            cfg_ids = [
                r[0]
                for r in con.execute(
                    "SELECT id FROM config WHERE tau = ?", (tau,)
                ).fetchall()
            ]
            n_cfg = len(cfg_ids)
            config_counts[tau] = n_cfg
            total_configs += n_cfg

            tau_miss: dict[str, float] = {}
            for axis in AXES:
                present = con.execute(
                    "SELECT COUNT(DISTINCT o.config_id) "
                    "FROM observation o JOIN config c ON c.id = o.config_id "
                    f"WHERE c.tau = ? AND o.axis = ? AND o.confidence IN ({placeholders}) "
                    "AND o.value_num IS NOT NULL",
                    (tau, axis, *kappa),
                ).fetchone()[0]
                overall_present[axis] += present
                tau_miss[axis] = 1.0 - (present / n_cfg) if n_cfg else 1.0
            per_tau[tau] = tau_miss

        overall = {
            axis: (1.0 - (overall_present[axis] / total_configs) if total_configs else 1.0)
            for axis in AXES
        }
    finally:
        con.close()

    config_counts["__total__"] = total_configs
    return {
        "provenance": "descriptive",
        "kappa": list(kappa),
        "per_tau": per_tau,
        "overall": overall,
        "config_counts": config_counts,
    }


# ---------------------------------------------------------------------------
# 8. κ-sensitivity (H3)
# ---------------------------------------------------------------------------


def sensitivity_kappa(
    sub: Substrate,
    phi: Phi = Phi.POINT,
    n_boot: int = 1000,
) -> dict:
    """Re-run the map under three κ policies and report the underdetermined shift.

    Sweeps κ ∈ {('H','M'), ('H',), ('H','M','L')} (H3). For each policy, computes
    the *overall* underdetermined fraction — averaged over all (τ × regime) cells —
    and reports it alongside the per-policy full map summary so the shift is
    auditable.

    Note: thresholds are re-grounded per κ (looser κ pools more observations),
    so the query battery itself moves slightly with κ — this is intentional: the
    whole pipeline (grid + verdicts) reacts to the confidence policy.

    Returns::

        {
          "phi": <phi>,
          "by_kappa": {
              "H+M": {"underdetermined_overall": f, "by_label_overall": {...}},
              ...
          },
          "underdetermined_shift": {"<policy>": frac, ...},
        }
    """
    by_kappa: dict[str, dict] = {}
    shift: dict[str, float] = {}

    for kappa in _KAPPA_SWEEP:
        key = "+".join(kappa)
        m = build_map(sub, kappa=kappa, phi=phi, n_boot=n_boot)
        # Average each label fraction over all (τ × regime) cells.
        sums = dict.fromkeys(_LABELS, 0.0)
        n_cells = 0
        for regimes in m.values():
            for cell in regimes.values():
                for lab in _LABELS:
                    sums[lab] += cell["fractions"][lab]
                n_cells += 1
        by_label = {
            lab: (sums[lab] / n_cells if n_cells else 0.0) for lab in _LABELS
        }
        und = by_label[Decidability.UNDERDETERMINED.value]
        by_kappa[key] = {
            "underdetermined_overall": und,
            "by_label_overall": by_label,
            "n_cells": n_cells,
        }
        shift[key] = und

    return {
        "phi": phi.value if isinstance(phi, Phi) else str(phi),
        "by_kappa": by_kappa,
        "underdetermined_shift": shift,
    }


__all__ = [
    "ARCHETYPES",
    "AXES",
    "blind_spot_report",
    "bootstrap_ci",
    "build_map",
    "generate_queries",
    "observed_thresholds",
    "run_cell",
    "sensitivity_kappa",
]
